# Generated by Django 5.1.4 on 2024-12-13 03:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='department',
            name='date_added',
        ),
        migrations.RemoveField(
            model_name='department',
            name='date_updated',
        ),
    ]
