# Generated by Django 5.1.4 on 2024-12-13 14:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_remove_department_date_added_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='admin',
            name='date_added',
        ),
        migrations.RemoveField(
            model_name='admin',
            name='date_updated',
        ),
        migrations.RemoveField(
            model_name='employees',
            name='date_added',
        ),
        migrations.RemoveField(
            model_name='employees',
            name='date_updated',
        ),
        migrations.RemoveField(
            model_name='position',
            name='date_added',
        ),
        migrations.RemoveField(
            model_name='position',
            name='date_updated',
        ),
    ]
