# Generated by Django 5.1.4 on 2024-12-16 11:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_departmenthead'),
    ]

    operations = [
        migrations.CreateModel(
            name='LeaveType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('leavetype', models.TextField()),
            ],
        ),
        migrations.AlterField(
            model_name='admin',
            name='contact',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='departmenthead',
            name='contact',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='employees',
            name='contact',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='employees',
            name='gender',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='Leave',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('from_date', models.DateField()),
                ('to_date', models.DateField()),
                ('days_no', models.IntegerField()),
                ('reason', models.TextField()),
                ('status', models.IntegerField()),
                ('emp_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.employees')),
                ('leavetype_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.leavetype')),
            ],
        ),
    ]
