# Generated by Django 5.1.4 on 2024-12-16 11:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_leavetype_alter_admin_contact_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Clients',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(blank=True, max_length=100)),
                ('fullname', models.TextField()),
                ('company_name', models.TextField()),
                ('projects_no', models.IntegerField()),
                ('email', models.TextField()),
                ('status', models.IntegerField()),
            ],
        ),
    ]
