# Generated by Django 5.1.3 on 2024-12-16 13:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_clientcompany_trainingtype_projects_training'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='position',
            name='description',
        ),
        migrations.AddField(
            model_name='position',
            name='department_id',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='app.department'),
        ),
    ]
