# Generated by Django 5.1.4 on 2024-12-16 13:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_remove_position_description_position_department_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employees',
            name='department_id',
        ),
    ]
