# Generated by Django 5.1.4 on 2024-12-17 02:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0010_remove_employees_department_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='Hr',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='D:\\Captures')),
                ('code', models.CharField(blank=True, max_length=100)),
                ('firstname', models.TextField()),
                ('lastname', models.TextField()),
                ('gender', models.IntegerField(blank=True, null=True)),
                ('dob', models.DateField(blank=True, null=True)),
                ('contact', models.IntegerField()),
                ('address', models.TextField()),
                ('email', models.TextField()),
                ('salary', models.FloatField(default=0)),
            ],
        ),
    ]
