# Generated by Django 5.1.4 on 2024-12-17 03:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0011_hr'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='hr',
            name='image',
        ),
    ]
