# Generated by Django 5.1.4 on 2024-12-17 03:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0012_remove_hr_image'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Hr',
        ),
    ]
