# Generated by Django 5.1.4 on 2024-12-17 14:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0013_delete_hr'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Leave',
            new_name='EmployeeLeave',
        ),
        migrations.CreateModel(
            name='AdminLeave',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('from_date', models.DateField()),
                ('to_date', models.DateField()),
                ('days_no', models.IntegerField()),
                ('reason', models.TextField()),
                ('status', models.IntegerField()),
                ('adm_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.admin')),
                ('leavetype_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.leavetype')),
            ],
        ),
    ]
