# Generated by Django 5.1.4 on 2024-12-18 09:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0014_rename_leave_employeeleave_adminleave'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='projects',
            name='department_id',
        ),
        migrations.AddField(
            model_name='projects',
            name='emp_id',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='app.employees'),
        ),
        migrations.AddField(
            model_name='projects',
            name='position_id',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='app.position'),
        ),
    ]
