# Generated by Django 5.1.4 on 2024-12-18 10:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0019_alter_projects_position_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projects',
            name='emp_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.employees'),
        ),
        migrations.AlterField(
            model_name='projects',
            name='position_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.position'),
        ),
    ]
