# Generated by Django 5.1.4 on 2024-12-18 10:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0021_projectss_delete_projects'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Projectss',
        ),
    ]
