# Generated by Django 5.1.4 on 2024-12-22 08:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0026_projects'),
    ]

    operations = [
        migrations.DeleteModel(
            name='L',
        ),
    ]
