# Generated by Django 5.1.4 on 2024-12-22 09:13

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0027_delete_l'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='training',
            name='cost',
        ),
        migrations.AddField(
            model_name='training',
            name='batch_time',
            field=models.TimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='trainingtype',
            name='cost',
            field=models.FloatField(default=0),
        ),
    ]
