# Generated by Django 5.1.4 on 2025-01-10 03:11

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0031_alter_employeeleave_emp_id_alter_projects_emp_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='adminleave',
            name='adm_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.RemoveField(
            model_name='employeeleave',
            name='status',
        ),
        migrations.DeleteModel(
            name='Admin',
        ),
    ]
