# Generated by Django 5.1.4 on 2025-01-10 04:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0032_alter_adminleave_adm_id_remove_employeeleave_status_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmpNotififaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField()),
                ('message', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='HrNotififaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField()),
                ('message', models.TextField()),
            ],
        ),
        migrations.AddField(
            model_name='employeeleave',
            name='status',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='adminleave',
            name='status',
            field=models.IntegerField(null=True),
        ),
    ]
